# Generated by Django 4.2.13 on 2024-06-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_initial_deposit_date_userbankaccount_initial_deposite_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankruptStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bankrupt', models.BooleanField(default=False)),
            ],
        ),
    ]
